import { redirect } from 'next/navigation'
import Link from 'next/link'
import { createClient } from '@/lib/supabase/server'
import { createAdminClient } from '@/lib/supabase/admin'
import { ProjectNav } from '@/components/ProjectNav'
import { StatusBadge } from '@/components/StatusBadge'
import { PlanApproveButton } from '@/components/PlanApproveButton'

type Params = { params: Promise<{ projectId: string }> }

export default async function PlanPage({ params }: Params) {
  const { projectId } = await params
  const supabase = await createClient()
  const { data: { user } } = await supabase.auth.getUser()
  if (!user) redirect('/auth')

  const admin = createAdminClient()
  const { data: dbUser } = await admin.from('users').select('id').eq('github_user_id', parseInt(user.user_metadata?.provider_id ?? '0', 10)).single()
  if (!dbUser) redirect('/auth')

  const { data: project } = await admin.from('projects').select('*').eq('id', projectId).eq('owner_id', dbUser.id).single()
  if (!project) redirect('/projects')

  const { data: plans } = await admin.from('plans').select('*').eq('project_id', projectId).order('version', { ascending: false })
  const activePlan = plans?.find((p: any) => p.status === 'approved') ?? plans?.[0] ?? null

  const { data: tasks } = activePlan
    ? await admin.from('tasks').select('id, display_id, title, status, priority, risk, task_dependencies!task_dependencies_task_id_fkey(depends_on_task_id)').eq('plan_id', activePlan.id).order('priority', { ascending: false })
    : { data: [] }

  return (
    <div style={{ minHeight: '100vh' }}>
      <header style={{ padding: '0.75rem 1.5rem', borderBottom: '1px solid var(--border)', background: 'var(--bg-surface)', display: 'flex', alignItems: 'center', gap: '1rem' }}>
        <Link href="/projects" style={{ color: 'var(--text-muted)', fontSize: '13px' }}>← Projects</Link>
        <span style={{ color: 'var(--border)' }}>·</span>
        <Link href={`/projects/${projectId}`} style={{ fontWeight: 600, color: 'var(--text)' }}>{project.repository_owner}/{project.repository_name}</Link>
      </header>
      <ProjectNav projectId={projectId} active="Plan" />
      <main style={{ maxWidth: '900px', margin: '0 auto', padding: '1.5rem' }}>
        {/* Plan version selector */}
        {plans?.length ? (
          <div style={{ display: 'flex', gap: '0.5rem', marginBottom: '1.5rem', flexWrap: 'wrap', alignItems: 'center' }}>
            {plans.map((p: any) => (
              <span key={p.id} style={{ fontSize: '13px' }}>
                v{p.version} <StatusBadge status={p.status} size="sm" />
              </span>
            ))}
          </div>
        ) : null}

        {!activePlan ? (
          <div style={{ padding: '3rem', textAlign: 'center', color: 'var(--text-muted)', border: '1px dashed var(--border)', borderRadius: 'var(--radius)' }}>
            No plans yet. Use the CLI to generate a plan, or create tasks manually.
          </div>
        ) : (
          <>
            <div style={{ padding: '1rem', border: '1px solid var(--border)', borderRadius: 'var(--radius)', background: 'var(--bg-surface)', marginBottom: '1.5rem', display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
              <div>
                <div style={{ display: 'flex', alignItems: 'center', gap: '0.75rem', marginBottom: '0.25rem' }}>
                  <span style={{ fontWeight: 700, fontSize: '1.1rem' }}>Plan v{activePlan.version}</span>
                  <StatusBadge status={activePlan.status} />
                </div>
                {activePlan.goal && <p style={{ color: 'var(--text-muted)', fontSize: '13px' }}>{activePlan.goal}</p>}
                {activePlan.generated_by && <p style={{ fontSize: '12px', color: 'var(--text-muted)' }}>Generated by: {activePlan.generated_by}</p>}
              </div>
              {activePlan.status === 'draft' && (
                <PlanApproveButton planId={activePlan.id} projectId={projectId} />
              )}
              {activePlan.status === 'approved' && activePlan.approved_at && (
                <span style={{ fontSize: '12px', color: 'var(--green)' }}>
                  Approved {new Date(activePlan.approved_at).toLocaleString()}
                </span>
              )}
            </div>

            {/* Task list */}
            <h2 style={{ fontSize: '14px', fontWeight: 600, marginBottom: '0.75rem' }}>Tasks ({tasks?.length ?? 0})</h2>
            <div style={{ border: '1px solid var(--border)', borderRadius: 'var(--radius)', overflow: 'hidden' }}>
              <table style={{ width: '100%', borderCollapse: 'collapse' }}>
                <thead>
                  <tr style={{ background: 'var(--bg-elevated)', fontSize: '12px', color: 'var(--text-muted)' }}>
                    <th style={{ padding: '0.5rem 1rem', textAlign: 'left', width: '90px' }}>ID</th>
                    <th style={{ padding: '0.5rem 1rem', textAlign: 'left' }}>Title</th>
                    <th style={{ padding: '0.5rem 1rem', textAlign: 'left', width: '110px' }}>Status</th>
                    <th style={{ padding: '0.5rem 1rem', textAlign: 'left', width: '60px' }}>Risk</th>
                    <th style={{ padding: '0.5rem 1rem', textAlign: 'left', width: '80px' }}>Deps</th>
                  </tr>
                </thead>
                <tbody>
                  {tasks?.map((t: any) => (
                    <tr key={t.id} style={{ borderTop: '1px solid var(--border)' }}>
                      <td style={{ padding: '0.5rem 1rem', fontFamily: 'monospace', fontSize: '12px' }}>
                        <Link href={`/projects/${projectId}/tasks/${t.id}`} style={{ color: 'var(--accent)' }}>{t.display_id}</Link>
                      </td>
                      <td style={{ padding: '0.5rem 1rem', fontSize: '13px' }}>
                        <Link href={`/projects/${projectId}/tasks/${t.id}`} style={{ color: 'var(--text)' }}>{t.title}</Link>
                      </td>
                      <td style={{ padding: '0.5rem 1rem' }}><StatusBadge status={t.status} size="sm" /></td>
                      <td style={{ padding: '0.5rem 1rem', fontSize: '12px', color: 'var(--text-muted)' }}>{t.risk ?? '—'}</td>
                      <td style={{ padding: '0.5rem 1rem', fontSize: '12px', color: 'var(--text-muted)' }}>
                        {t.task_dependencies?.length ?? 0}
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          </>
        )}
      </main>
    </div>
  )
}
